version: '3.8'

services:
  server:
    build: .
    # runtime: nvidia  # Remove this line if not using an NVIDIA GPU
    ports:
      - "8000:80"
    volumes:
      - $PWD:/app:delegated
      - /Users/matthew.h.clark/.cache/huggingface/hub/:/models
    environment:
      - MODEL_NAME=deepseek-ai/DeepSeek-R1-Distill-Qwen-32B
      - MODEL_PATH=/models/deepseek-ai/DeepSeek-R1-Distill-Qwen-32B
    command: python main.py server

  client:
    build: .
    stdin_open: true
    tty: true
    environment:
      - SERVER_URL=http://server:8008/query
    command: python main.py tts
    depends_on:
      - server

  evaluate:
    build: .
    environment:
      - SERVER_URL=http://server:8000
    depends_on:
      - server
    command: python evaluate.py